INSERT INTO TODOLIST (LIBELLE) VALUES ('Course');

INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Acheter Poisson','TODO',0);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Acheter Viande','TODO',0);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Acheter Légume','TODO',0);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Acheter Miel','TODO',0);

INSERT INTO TODOLIST (LIBELLE) VALUES ('Cinema');

INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Voir Transformers','TODO',1);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Voir James Bonds','TODO',1);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Voir Une nuit en enfer','TODO',1);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Voir Blue magic','TODO',1);

INSERT INTO TODOLIST (LIBELLE) VALUES ('Pièce auto');

INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Remplacer embrayage','TODO',2);
INSERT INTO TASK (NAME,STATE,IDTODOLIST) VALUES ('Vendre retro viseur','TODO',2);

INSERT INTO TODOLIST (LIBELLE) VALUES ('Cours informatique');

