DROP TABLE TODOLIST IF EXISTS;
CREATE TABLE TODOLIST
(
    ID integer PRIMARY KEY NOT NULL,
    LIBELLE varchar(200) NOT NULL
);

DROP TABLE TASK IF EXISTS;
CREATE TABLE TASK
(
    ID integer PRIMARY KEY,
    NAME varchar(200) NOT NULL,
    IDTODOLIST integer,
    STATE varchar(30)
 --   CONSTRAINT TASK_TODOLIST_ID_FK FOREIGN KEY (IDTODOLIST) REFERENCES TODOLIST (ID)
);

